# ################################
# Model: VGG2 + LiGRU with time pooling for efficiency
# Additions: TimeDomainSpecAugment
# Authors: Mirco Ravanelli & Peter Plantinga 2020
# ################################

# Seed needs to be set at top of yaml, before objects with parameters are made
seed: 1245
__set_seed: !!python/object/apply:torch.manual_seed [!ref <seed>]
output_folder: !ref results/<seed>
test_stats_file: !ref <output_folder>/test_stats.txt
save_folder: !ref <output_folder>/save
train_log: !ref <output_folder>/train_log.txt
encoder_save_file: ./encoder.txt

# Data files
data_folder: !PLACEHOLDER
train_annotation: ./train.json
valid_annotation: ./valid.json
test_annotation: ./test.json

# Training parameters
number_of_epochs: 50
batch_size: 16
learning_rate: 0.0001
alignment_weight: 0.0
dataloader_opts:
    batch_size: !ref <batch_size>

# Feature parameters
sample_rate: 16000
n_fft: 400
n_mels: 40
output_neurons: 40

epoch_counter: !new:speechbrain.utils.epoch_loop.EpochCounter
    limit: !ref <number_of_epochs>

normalize: !new:speechbrain.processing.features.InputNormalization

augmentation: !new:speechbrain.lobes.augment.TimeDomainSpecAugment
    sample_rate: !ref <sample_rate>
    speeds: [95, 100, 105]

compute_features: !new:speechbrain.lobes.features.Fbank
    sample_rate: !ref <sample_rate>
    n_fft: !ref <n_fft>
    n_mels: !ref <n_mels>

recognizer: !new:time_freq_crdnn.TimeFreqCRDNN
    input_size: !ref <n_mels>
    cnn_channels: [64, 128]
    rnn_neurons: 256
    rnn_bidirectional: True
    dnn_neurons: 256
    dropout: 0.2

recognizer_output: !new:speechbrain.nnet.linear.Linear
    input_size: !ref <recognizer[dnn_neurons]>
    n_neurons: !ref <output_neurons>
    bias: True

log_softmax: !new:speechbrain.nnet.activations.Softmax
    apply_log: True

bce_loss: !name:speechbrain.nnet.losses.BCE_loss

modules:
    recognizer: !ref <recognizer>
    recognizer_output: !ref <recognizer_output>
    normalize: !ref <normalize>

opt_class: !name:torch.optim.Adam
    lr: !ref <learning_rate>

lr_annealing: !new:speechbrain.nnet.schedulers.NewBobScheduler
    initial_value: !ref <learning_rate>
    improvement_threshold: 0.0025
    annealing_factor: 0.8
    patient: 0

checkpointer: !new:speechbrain.utils.checkpoints.Checkpointer
    checkpoints_dir: !ref <save_folder>
    recoverables:
        recognizer: !ref <recognizer>
        recognizer_output: !ref <recognizer_output>
        scheduler: !ref <lr_annealing>
        normalizer: !ref <normalize>
        counter: !ref <epoch_counter>

train_logger: !new:speechbrain.utils.train_logger.FileTrainLogger
    save_file: !ref <train_log>

per_computer: !name:speechbrain.utils.metric_stats.ErrorRateStats
